table 'Respuestas formulario'
	lineageTag: 9caa6551-af15-4726-a671-91d2bbc1eb4d

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 2da73aa0-df1f-458f-a262-436ec80930df
		summarizeBy: count
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column 'Hora d''inici'
		dataType: dateTime
		formatString: General Date
		lineageTag: f14038d5-d106-4acb-b5e2-9ec896cb58d7
		summarizeBy: none
		sourceColumn: Hora d'inici

		variation Variación
			isDefault
			relationship: 9e75fd18-07cf-44d2-813f-798e2ddda338
			defaultHierarchy: LocalDateTable_f8797aad-9228-45b7-8b31-4dc8a12e8297.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Hora de finalització'
		dataType: dateTime
		formatString: General Date
		lineageTag: 73408745-6f34-46d1-ba4c-51b89218021c
		summarizeBy: none
		sourceColumn: Hora de finalització

		variation Variación
			isDefault
			relationship: 365dbb5a-a441-4aa2-bce8-d0003634a209
			defaultHierarchy: LocalDateTable_a2597404-969f-4dd1-a94a-a6e096635b79.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Correu
		dataType: string
		lineageTag: 76f4465d-dcec-4355-9676-fc12a3648f93
		summarizeBy: none
		sourceColumn: Correu

		annotation SummarizationSetBy = Automatic

	column Nom
		dataType: string
		lineageTag: a3b71a05-8d25-4804-8ccb-8da45b26bd44
		summarizeBy: none
		sourceColumn: Nom

		annotation SummarizationSetBy = Automatic

	column 'Nombre de la persona de contacto'
		dataType: string
		lineageTag: 79de1a21-39af-4e32-a274-920672c9447d
		summarizeBy: none
		sourceColumn: Nombre de la persona de contacto

		annotation SummarizationSetBy = Automatic

	column 'Email de contacto'
		dataType: string
		lineageTag: cb2e28b0-3959-4698-8a9e-8523b3c7d0e6
		summarizeBy: none
		sourceColumn: Email de contacto

		annotation SummarizationSetBy = Automatic

	column Compañía
		dataType: string
		lineageTag: a3dbd4c9-a25d-4a97-8f95-a4adada32310
		summarizeBy: none
		sourceColumn: Compañía

		annotation SummarizationSetBy = Automatic

	column 'Sector / actividad'
		dataType: string
		lineageTag: 0c13c680-6aa5-48d7-a66e-2517889e3473
		summarizeBy: none
		sourceColumn: Sector / actividad

		annotation SummarizationSetBy = Automatic

	column 'Centros de trabajo'
		dataType: int64
		formatString: 0
		lineageTag: 216644e9-9d5a-47ee-b423-0723d6062fe2
		summarizeBy: sum
		sourceColumn: Centros de trabajo

		annotation SummarizationSetBy = Automatic

	column Plantilla
		dataType: string
		lineageTag: ff97f486-e265-4ec3-b3ca-67c6e220fea5
		summarizeBy: none
		sourceColumn: Plantilla

		annotation SummarizationSetBy = Automatic

	column 'Medidas LGTBI.¿La empresa cuenta con medidas LGTBI implantadas cuando resultan exigibles? '
		dataType: string
		lineageTag: a993a59b-bbb4-4c94-85bb-c6ab9523c117
		summarizeBy: none
		sourceColumn: "Medidas LGTBI.¿La empresa cuenta con medidas LGTBI implantadas cuando resultan exigibles? "

		annotation SummarizationSetBy = Automatic

	column 'Comité de Seguridad y Salud.¿El Comité de Seguridad y Salud se reúne trimestralmente en centros o empresas obligadas?'
		dataType: string
		lineageTag: bbc1baaa-b984-4cf8-9c53-bdc22c899b69
		summarizeBy: none
		sourceColumn: Comité de Seguridad y Salud.¿El Comité de Seguridad y Salud se reúne trimestralmente en centros o empresas obligadas?

		annotation SummarizationSetBy = Automatic

	column 'Comité de Seguridad y Salud.¿Se levantan actas con asistentes, materias, acuerdos, responsables y plazos? '
		dataType: string
		lineageTag: af321934-f3db-407e-b34d-2936b7745417
		summarizeBy: none
		sourceColumn: "Comité de Seguridad y Salud.¿Se levantan actas con asistentes, materias, acuerdos, responsables y plazos? "

		annotation SummarizationSetBy = Automatic

	column 'Cuota de reserva discapacidad 2%.¿La empresa controla periódicamente si alcanza 50 o más personas trabajadoras a efectos de cuota de discapacidad? '
		dataType: string
		lineageTag: 692251bc-3e6c-4a7a-a0fc-fc155ce0e06a
		summarizeBy: none
		sourceColumn: "Cuota de reserva discapacidad 2%.¿La empresa controla periódicamente si alcanza 50 o más personas trabajadoras a efectos de cuota de discapacidad? "

		annotation SummarizationSetBy = Automatic

	column 'Cuota de reserva discapacidad 2%.¿Cumple la cuota de reserva del 2% o dispone de medidas alternativas autorizadas?'
		dataType: string
		lineageTag: bdd15cc9-5243-4e79-8753-e156c79dbe73
		summarizeBy: none
		sourceColumn: Cuota de reserva discapacidad 2%.¿Cumple la cuota de reserva del 2% o dispone de medidas alternativas autorizadas?

		annotation SummarizationSetBy = Automatic

	column 'Cuota de reserva discapacidad 2%.¿Existe seguimiento específico cuando hay crecimiento, reorganización o cambios de plantilla? '
		dataType: string
		lineageTag: ef2d0983-37dc-41df-9ac2-3d8f0bc4d7a0
		summarizeBy: none
		sourceColumn: "Cuota de reserva discapacidad 2%.¿Existe seguimiento específico cuando hay crecimiento, reorganización o cambios de plantilla? "

		annotation SummarizationSetBy = Automatic

	column 'Plan de Igualdad.¿La empresa ha verificado formalmente el cómputo de plantilla a 30 de junio y 31 de diciembre? '
		dataType: string
		lineageTag: 71b68daa-6265-4f1b-86b1-a545f93a6fd1
		summarizeBy: none
		sourceColumn: "Plan de Igualdad.¿La empresa ha verificado formalmente el cómputo de plantilla a 30 de junio y 31 de diciembre? "

		annotation SummarizationSetBy = Automatic

	column 'Plan de Igualdad.¿Dispone de Plan de Igualdad cuando resulta obligatorio por plantilla, convenio o requerimiento? '
		dataType: string
		lineageTag: 827d303e-6189-4935-a472-641e8c48f20f
		summarizeBy: none
		sourceColumn: "Plan de Igualdad.¿Dispone de Plan de Igualdad cuando resulta obligatorio por plantilla, convenio o requerimiento? "

		annotation SummarizationSetBy = Automatic

	column 'Plan de Igualdad.¿La Comisión de Seguimiento, si existe, se reúne y levanta acta al menos de forma periódica? '
		dataType: string
		lineageTag: be647fd1-1321-40fd-810c-402aa5783cb7
		summarizeBy: none
		sourceColumn: "Plan de Igualdad.¿La Comisión de Seguimiento, si existe, se reúne y levanta acta al menos de forma periódica? "

		annotation SummarizationSetBy = Automatic

	column 'Canal interno de información / denuncias.¿El canal de denuncias/procedimiento interno garantiza confidencialidad, plazos, investigación y no represalia?'
		dataType: string
		lineageTag: ccbd0028-b5d0-4a08-8d07-6d1fb011373e
		summarizeBy: none
		sourceColumn: Canal interno de información / denuncias.¿El canal de denuncias/procedimiento interno garantiza confidencialidad, plazos, investigación y no represalia?

		annotation SummarizationSetBy = Automatic

	column 'Canal interno de información / denuncias.¿Se han comunicado los canales y protocolos a toda la plantilla?'
		dataType: string
		lineageTag: b2f72e6a-9d21-45a9-8446-e58026c80119
		summarizeBy: none
		sourceColumn: Canal interno de información / denuncias.¿Se han comunicado los canales y protocolos a toda la plantilla?

		annotation SummarizationSetBy = Automatic

	column 'Canal interno de información / denuncias.¿Existen registros de denuncias, investigaciones, resoluciones, formaciones y medidas correctoras?'
		dataType: string
		lineageTag: a305645c-9372-415e-a8b3-e2938aade0ea
		summarizeBy: none
		sourceColumn: Canal interno de información / denuncias.¿Existen registros de denuncias, investigaciones, resoluciones, formaciones y medidas correctoras?

		annotation SummarizationSetBy = Automatic

	column 'Acuerdo de trabajo a distancia.¿Los acuerdos de teletrabajo recogen medios, gastos, jornada, disponibilidad, reversibilidad y PRL?'
		dataType: string
		lineageTag: f8baab05-b626-40c7-bfa4-8aa5e502e82d
		summarizeBy: none
		sourceColumn: Acuerdo de trabajo a distancia.¿Los acuerdos de teletrabajo recogen medios, gastos, jornada, disponibilidad, reversibilidad y PRL?

		annotation SummarizationSetBy = Automatic

	column 'CAE – coordinación de actividades empresariales.¿La CAE con contratas, proveedores o clientes críticos está documentada y actualizada?'
		dataType: string
		lineageTag: 8517c8ce-45e6-4731-b548-d9e8ce464bb0
		summarizeBy: none
		sourceColumn: CAE – coordinación de actividades empresariales.¿La CAE con contratas, proveedores o clientes críticos está documentada y actualizada?

		annotation SummarizationSetBy = Automatic

	column 'Ayudas, subvenciones y contratación pública.¿Se conserva evidencia del cumplimiento ante ayudas públicas, licitaciones o contratación pública? '
		dataType: string
		lineageTag: b5af68ab-302d-46cb-b7fb-6177cecd9e85
		summarizeBy: none
		sourceColumn: "Ayudas, subvenciones y contratación pública.¿Se conserva evidencia del cumplimiento ante ayudas públicas, licitaciones o contratación pública? "

		annotation SummarizationSetBy = Automatic

	column 'Ayudas, subvenciones y contratación pública.¿Se coordinan RRHH, legal y compras para evitar riesgos en contratación pública? '
		dataType: string
		lineageTag: eb23410c-3119-45d5-9935-286d5514bae7
		summarizeBy: none
		sourceColumn: "Ayudas, subvenciones y contratación pública.¿Se coordinan RRHH, legal y compras para evitar riesgos en contratación pública? "

		annotation SummarizationSetBy = Automatic

	column 'Plan de Movilidad Sostenible al Trabajo.¿La empresa ha analizado si le aplican obligaciones de movilidad sostenible antes de diciembre de 2026?'
		dataType: string
		lineageTag: a4708b35-8da1-48f1-ae76-d5cf5d0382b7
		summarizeBy: none
		sourceColumn: Plan de Movilidad Sostenible al Trabajo.¿La empresa ha analizado si le aplican obligaciones de movilidad sostenible antes de diciembre de 2026?

		annotation SummarizationSetBy = Automatic

	column 'Plan de Movilidad Sostenible al Trabajo.¿Existen medidas de movilidad segura/sostenible o una hoja de ruta de negociación e implantación?'
		dataType: string
		lineageTag: 7808fc99-57b8-437b-9d4f-556f3da0b843
		summarizeBy: none
		sourceColumn: Plan de Movilidad Sostenible al Trabajo.¿Existen medidas de movilidad segura/sostenible o una hoja de ruta de negociación e implantación?

		annotation SummarizationSetBy = Automatic

	column 'Movilidad / desplazamientos internacionales.¿Los desplazamientos nacionales o internacionales cuentan con cartas, A1/certificados y control de días? '
		dataType: string
		lineageTag: 1b4a3fa1-e066-40ae-a0a1-75e2b98d88a2
		summarizeBy: none
		sourceColumn: "Movilidad / desplazamientos internacionales.¿Los desplazamientos nacionales o internacionales cuentan con cartas, A1/certificados y control de días? "

		annotation SummarizationSetBy = Automatic

	column 'Movilidad / desplazamientos internacionales.¿Se han revisado riesgos laborales, fiscales, migratorios y de Seguridad Social en movilidad internacional? '
		dataType: string
		lineageTag: 8747f82b-5d86-40fc-8299-0e4ef65a218c
		summarizeBy: none
		sourceColumn: "Movilidad / desplazamientos internacionales.¿Se han revisado riesgos laborales, fiscales, migratorios y de Seguridad Social en movilidad internacional? "

		annotation SummarizationSetBy = Automatic

	column 'Movilidad / desplazamientos internacionales.¿Existe coordinación entre Laboral, Fiscal, Payroll y movilidad internacional?'
		dataType: string
		lineageTag: ef0b64fa-d662-4964-97ef-ea9cf1136b06
		summarizeBy: none
		sourceColumn: Movilidad / desplazamientos internacionales.¿Existe coordinación entre Laboral, Fiscal, Payroll y movilidad internacional?

		annotation SummarizationSetBy = Automatic

	column '¿Existe coordinación entre Laboral, Fiscal, Payroll y movilidad internacional? .¿Existe un sistema de registro diario de jornada que refleje inicio y fin de la jornada real? '
		dataType: string
		lineageTag: da104286-3059-4347-9bb8-9318c292fc9b
		summarizeBy: none
		sourceColumn: "¿Existe coordinación entre Laboral, Fiscal, Payroll y movilidad internacional? .¿Existe un sistema de registro diario de jornada que refleje inicio y fin de la jornada real? "

		annotation SummarizationSetBy = Automatic

	column '¿Existe coordinación entre Laboral, Fiscal, Payroll y movilidad internacional? .¿Los registros se conservan durante cuatro años y son accesibles cuando proceda? '
		dataType: string
		lineageTag: 31926d75-fc2a-480b-907a-fd23f55d8bf4
		summarizeBy: none
		sourceColumn: "¿Existe coordinación entre Laboral, Fiscal, Payroll y movilidad internacional? .¿Los registros se conservan durante cuatro años y son accesibles cuando proceda? "

		annotation SummarizationSetBy = Automatic

	column 'Calendario, jornada, descansos y vacaciones.¿La empresa controla horas extra, excesos de jornada, descansos, turnos y disponibilidad fuera de horario?'
		dataType: string
		lineageTag: 9de15b67-9475-4d06-bc45-2966ce635986
		summarizeBy: none
		sourceColumn: Calendario, jornada, descansos y vacaciones.¿La empresa controla horas extra, excesos de jornada, descansos, turnos y disponibilidad fuera de horario?

		annotation SummarizationSetBy = Automatic

	column 'Calendario, jornada, descansos y vacaciones.¿El calendario laboral anual está actualizado y comunicado conforme a jornada, festivos y convenio?'
		dataType: string
		lineageTag: 70d0b53c-0501-41a2-9ab6-2f068c35db03
		summarizeBy: none
		sourceColumn: Calendario, jornada, descansos y vacaciones.¿El calendario laboral anual está actualizado y comunicado conforme a jornada, festivos y convenio?

		annotation SummarizationSetBy = Automatic

	column 'Calendario, jornada, descansos y vacaciones.¿Las vacaciones se comunican y planifican con antelación mínima suficiente y evidencia documental? '
		dataType: string
		lineageTag: 0bd771e1-0361-4ab1-9bfd-e45028984e5c
		summarizeBy: none
		sourceColumn: "Calendario, jornada, descansos y vacaciones.¿Las vacaciones se comunican y planifican con antelación mínima suficiente y evidencia documental? "

		annotation SummarizationSetBy = Automatic

	column 'Protocolos permanentes y políticas internas.¿La empresa dispone de protocolos y políticas internas actualizadas, aprobadas y comunicadas? '
		dataType: string
		lineageTag: 4e88cdbb-60c5-4f22-a03c-44f2f048dbea
		summarizeBy: none
		sourceColumn: "Protocolos permanentes y políticas internas.¿La empresa dispone de protocolos y políticas internas actualizadas, aprobadas y comunicadas? "

		annotation SummarizationSetBy = Automatic

	column 'Protocolos permanentes y políticas internas.¿Se acredita la entrega, difusión o formación de las políticas a la plantilla y managers? '
		dataType: string
		lineageTag: 1c6d801e-91ee-4bd9-bc16-d59202c2056f
		summarizeBy: none
		sourceColumn: "Protocolos permanentes y políticas internas.¿Se acredita la entrega, difusión o formación de las políticas a la plantilla y managers? "

		annotation SummarizationSetBy = Automatic

	column 'Protocolos permanentes y políticas internas.¿Las políticas reflejan la práctica real de la empresa y no solo modelos genéricos? '
		dataType: string
		lineageTag: 9e6a48a8-272a-48c9-8853-8f08149f87bf
		summarizeBy: none
		sourceColumn: "Protocolos permanentes y políticas internas.¿Las políticas reflejan la práctica real de la empresa y no solo modelos genéricos? "

		annotation SummarizationSetBy = Automatic

	column 'Protocolos permanentes y políticas internas.¿Existe un responsable interno de mantenimiento y revisión periódica de documentación laboral? '
		dataType: string
		lineageTag: d27aacca-ff70-4419-84fe-a1895323ac99
		summarizeBy: none
		sourceColumn: "Protocolos permanentes y políticas internas.¿Existe un responsable interno de mantenimiento y revisión periódica de documentación laboral? "

		annotation SummarizationSetBy = Automatic

	column 'Protocolos permanentes y políticas internas.¿Se revisan las políticas cuando hay cambios normativos, organizativos o de convenio? '
		dataType: string
		lineageTag: eefac848-22d2-45df-8cd8-70c15eea11d2
		summarizeBy: none
		sourceColumn: "Protocolos permanentes y políticas internas.¿Se revisan las políticas cuando hay cambios normativos, organizativos o de convenio? "

		annotation SummarizationSetBy = Automatic

	column 'Registro retributivo.¿Existe registro retributivo anual actualizado e integrado con datos reales de nómina? '
		dataType: string
		lineageTag: 7520dc3c-f9e2-4fc5-b55f-6e40fb047eaa
		summarizeBy: none
		sourceColumn: "Registro retributivo.¿Existe registro retributivo anual actualizado e integrado con datos reales de nómina? "

		annotation SummarizationSetBy = Automatic

	column 'Registro retributivo.¿Se revisan brechas salariales, complementos, bonus y puestos de igual valor? '
		dataType: string
		lineageTag: 87f7459e-dd1e-44ac-8fc3-7b5604cb541b
		summarizeBy: none
		sourceColumn: "Registro retributivo.¿Se revisan brechas salariales, complementos, bonus y puestos de igual valor? "

		annotation SummarizationSetBy = Automatic

	column 'Protocolo / medidas frente al acoso.¿Existe protocolo frente al acoso sexual, por razón de sexo, moral y otras conductas inapropiadas?'
		dataType: string
		lineageTag: d83dacc2-315d-4e24-9062-4768f3233b90
		summarizeBy: none
		sourceColumn: Protocolo / medidas frente al acoso.¿Existe protocolo frente al acoso sexual, por razón de sexo, moral y otras conductas inapropiadas?

		annotation SummarizationSetBy = Automatic

	column 'Política de desconexión digital.¿La política de desconexión digital está implantada y es compatible con la práctica real?'
		dataType: string
		lineageTag: 24ccacc5-86d4-46aa-bf38-0658bea5d6cb
		summarizeBy: none
		sourceColumn: Política de desconexión digital.¿La política de desconexión digital está implantada y es compatible con la práctica real?

		annotation SummarizationSetBy = Automatic

	column 'Política de desconexión digital.¿La política de uso de medios tecnológicos informa sobre controles empresariales posibles?'
		dataType: string
		lineageTag: d4fdaeea-eea1-4187-8264-074c3bbc6382
		summarizeBy: none
		sourceColumn: Política de desconexión digital.¿La política de uso de medios tecnológicos informa sobre controles empresariales posibles?

		annotation SummarizationSetBy = Automatic

	column 'Política de desconexión digital.¿Se han revisado correo, dispositivos, videovigilancia, geolocalización o herramientas digitales de RRHH?'
		dataType: string
		lineageTag: 29bbedd1-3d0d-4a73-92b1-fd1e82e87a06
		summarizeBy: none
		sourceColumn: Política de desconexión digital.¿Se han revisado correo, dispositivos, videovigilancia, geolocalización o herramientas digitales de RRHH?

		annotation SummarizationSetBy = Automatic

	column 'Política de desconexión digital.¿Los managers conocen los límites de control, privacidad y proporcionalidad?'
		dataType: string
		lineageTag: 90c59221-0243-4d87-bd36-1bdf8410e7b5
		summarizeBy: none
		sourceColumn: Política de desconexión digital.¿Los managers conocen los límites de control, privacidad y proporcionalidad?

		annotation SummarizationSetBy = Automatic

	column 'PRL: evaluación, formación, vigilancia de la salud y EPIs.¿La evaluación de riesgos está actualizada respecto a centros, puestos y cambios organizativos? '
		dataType: string
		lineageTag: 1fa3ef5d-6a1e-4e6a-a615-5b392aa00051
		summarizeBy: none
		sourceColumn: "PRL: evaluación, formación, vigilancia de la salud y EPIs.¿La evaluación de riesgos está actualizada respecto a centros, puestos y cambios organizativos? "

		annotation SummarizationSetBy = Automatic

	column 'PRL: evaluación, formación, vigilancia de la salud y EPIs.¿Se acredita formación, información preventiva, vigilancia de la salud y entrega de EPIs cuando procede? '
		dataType: string
		lineageTag: 08d234c4-741c-4438-b861-95d1ad84865c
		summarizeBy: none
		sourceColumn: "PRL: evaluación, formación, vigilancia de la salud y EPIs.¿Se acredita formación, información preventiva, vigilancia de la salud y entrega de EPIs cuando procede? "

		annotation SummarizationSetBy = Automatic

	column 'Contratación, documentación laboral y payroll.¿Los contratos y anexos reflejan jornada, salario, puesto, centro, convenio y modalidad real? '
		dataType: string
		lineageTag: 3bdc65fb-d56d-47cf-950e-e399c3742e60
		summarizeBy: none
		sourceColumn: "Contratación, documentación laboral y payroll.¿Los contratos y anexos reflejan jornada, salario, puesto, centro, convenio y modalidad real? "

		annotation SummarizationSetBy = Automatic

	column 'Contratación, documentación laboral y payroll.¿Se revisan contratos temporales, fijos discontinuos, tiempo parcial, becarios, ETT y autónomos recurrentes? '
		dataType: string
		lineageTag: 17260e90-992d-4599-bc7d-fad357c78450
		summarizeBy: none
		sourceColumn: "Contratación, documentación laboral y payroll.¿Se revisan contratos temporales, fijos discontinuos, tiempo parcial, becarios, ETT y autónomos recurrentes? "

		annotation SummarizationSetBy = Automatic

	column 'Contratación, documentación laboral y payroll.¿Payroll aplica correctamente conceptos salariales, cotización, IRPF, permisos, IT y beneficios? '
		dataType: string
		lineageTag: 08e6d65b-5ebf-41b3-84f4-55c2ca6dd147
		summarizeBy: none
		sourceColumn: "Contratación, documentación laboral y payroll.¿Payroll aplica correctamente conceptos salariales, cotización, IRPF, permisos, IT y beneficios? "

		annotation SummarizationSetBy = Automatic

	column 'Contratación, documentación laboral y payroll.¿Se conservan comunicaciones, recibís, anexos, novaciones y documentación laboral relevante? '
		dataType: string
		lineageTag: 2e21f19f-a9b0-4b6a-bb96-637c0c24ed48
		summarizeBy: none
		sourceColumn: "Contratación, documentación laboral y payroll.¿Se conservan comunicaciones, recibís, anexos, novaciones y documentación laboral relevante? "

		annotation SummarizationSetBy = Automatic

	column 'Contratación, documentación laboral y payroll.¿La empresa tiene criterios homogéneos para sanciones, promociones, cambios de puesto y modificaciones sustanciales? '
		dataType: string
		lineageTag: 630c9501-60fb-4349-97b8-938908871f34
		summarizeBy: none
		sourceColumn: "Contratación, documentación laboral y payroll.¿La empresa tiene criterios homogéneos para sanciones, promociones, cambios de puesto y modificaciones sustanciales? "

		annotation SummarizationSetBy = Automatic

	column 'Evidencias, trazabilidad y preparación ante Inspección.¿La empresa puede acreditar cumplimiento con documentos fechados, firmados o comunicados? '
		dataType: string
		lineageTag: dddce936-474f-4d98-b8fa-455267667e4b
		summarizeBy: none
		sourceColumn: "Evidencias, trazabilidad y preparación ante Inspección.¿La empresa puede acreditar cumplimiento con documentos fechados, firmados o comunicados? "

		annotation SummarizationSetBy = Automatic

	column 'Evidencias, trazabilidad y preparación ante Inspección.¿Existe calendario interno de compliance laboral con responsables y plazos? '
		dataType: string
		lineageTag: 92817c06-c5d3-4d65-99c8-4ab8e86f8259
		summarizeBy: none
		sourceColumn: "Evidencias, trazabilidad y preparación ante Inspección.¿Existe calendario interno de compliance laboral con responsables y plazos? "

		annotation SummarizationSetBy = Automatic

	column 'Evidencias, trazabilidad y preparación ante Inspección.¿Se revisan periódicamente riesgos de Inspección de Trabajo, litigios, conflictos colectivos o auditorías? '
		dataType: string
		lineageTag: 400bfce3-6992-4427-a4be-91258b20e0e1
		summarizeBy: none
		sourceColumn: "Evidencias, trazabilidad y preparación ante Inspección.¿Se revisan periódicamente riesgos de Inspección de Trabajo, litigios, conflictos colectivos o auditorías? "

		annotation SummarizationSetBy = Automatic

	column 'Evidencias, trazabilidad y preparación ante Inspección.¿La Dirección recibe un reporting ejecutivo de riesgos laborales y acciones pendientes? '
		dataType: string
		lineageTag: eb090373-9878-4960-b573-2fc110c67df2
		summarizeBy: none
		sourceColumn: "Evidencias, trazabilidad y preparación ante Inspección.¿La Dirección recibe un reporting ejecutivo de riesgos laborales y acciones pendientes? "

		annotation SummarizationSetBy = Automatic

	column 'Evidencias, trazabilidad y preparación ante Inspección.¿Hay procedimiento de respuesta ante requerimientos de Inspección, reclamaciones o due diligence? '
		dataType: string
		lineageTag: 98f0c433-e97b-4b3e-9727-aa2582dac557
		summarizeBy: none
		sourceColumn: "Evidencias, trazabilidad y preparación ante Inspección.¿Hay procedimiento de respuesta ante requerimientos de Inspección, reclamaciones o due diligence? "

		annotation SummarizationSetBy = Automatic

	partition 'Respuestas formulario' = m
		mode: import
		source =
				let
				    Origen = SharePoint.Files("https://bovemontero-my.sharepoint.com/personal/smbi_bovemontero_com", [ApiVersion = 15]),
				    #"LABOUR COMPLIANCE HEALTH CHECK xlsx_https://bovemontero-my sharepoint com/personal/smbi_bovemontero_com/Documents/" = Origen{[Name="LABOUR COMPLIANCE HEALTH CHECK.xlsx",#"Folder Path"="https://bovemontero-my.sharepoint.com/personal/smbi_bovemontero_com/Documents/"]}[Content],
				    #"Libro de Excel importado" = Excel.Workbook(#"LABOUR COMPLIANCE HEALTH CHECK xlsx_https://bovemontero-my sharepoint com/personal/smbi_bovemontero_com/Documents/"),
				    #"OfficeForms Table_Table" = #"Libro de Excel importado"{[Item="OfficeForms.Table",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"OfficeForms Table_Table",{{"Hora de finalització", type datetime}, {"Hora d'inici", type datetime}, {"Id", Int64.Type}, {"Centros de trabajo", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

